// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoazahBids.Web.Data;

namespace MoazahBids.Web.Migrations
{
    [DbContext(typeof(BidsDbContext))]
    [Migration("20211015135033_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("MoazahBids.Domain.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCallDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("MoazahBids.Domain.Entities.BidItem", b =>
                {
                    b.Property<int>("BidId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("BidId", "Name");

                    b.ToTable("BidsItems");
                });

            modelBuilder.Entity("MoazahBids.Domain.Entities.BidOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTaxedPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BidId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("MoazahBids.Domain.Entities.BidOfferItem", b =>
                {
                    b.Property<int>("OfferId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvidableQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalTaxedPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("OfferId", "ItemName");

                    b.ToTable("OffersItems");
                });

            modelBuilder.Entity("MoazahBids.Domain.Entities.BidItem", b =>
                {
                    b.HasOne("MoazahBids.Domain.Entities.Bid", "Bid")
                        .WithMany("Items")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");
                });

            modelBuilder.Entity("MoazahBids.Domain.Entities.BidOffer", b =>
                {
                    b.HasOne("MoazahBids.Domain.Entities.Bid", "Bid")
                        .WithMany("Offers")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");
                });

            modelBuilder.Entity("MoazahBids.Domain.Entities.BidOfferItem", b =>
                {
                    b.HasOne("MoazahBids.Domain.Entities.BidOffer", "Offer")
                        .WithMany("ItemOffers")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("MoazahBids.Domain.Entities.Bid", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("MoazahBids.Domain.Entities.BidOffer", b =>
                {
                    b.Navigation("ItemOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
